#!/usr/bin/env sh
set -eu

APPDIR="${APPDIR:-$(dirname "$(readlink -f "$0")")}"

export PATH="$APPDIR/usr/bin:$PATH"
export XDG_DATA_DIRS="$APPDIR/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
export LD_LIBRARY_PATH="$APPDIR/usr/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
if [ -d "$APPDIR/usr/share/X11/xkb" ]; then
  export XKB_CONFIG_ROOT="$APPDIR/usr/share/X11/xkb"
fi

prepend_existing_path() {
  var="$1"
  dir="$2"
  [ -d "$dir" ] || return 0
  eval "current=\${$var:-}"
  if [ -n "$current" ]; then
    eval "export $var=\"$dir:\$current\""
  else
    eval "export $var=\"$dir\""
  fi
}

append_existing_path() {
  var="$1"
  dir="$2"
  [ -d "$dir" ] || return 0
  eval "current=\${$var:-}"
  if [ -n "$current" ]; then
    eval "export $var=\"\$current:$dir\""
  else
    eval "export $var=\"$dir\""
  fi
}

append_existing_path LD_LIBRARY_PATH /run/opengl-driver/lib
append_existing_path LD_LIBRARY_PATH /run/current-system/sw/share/nix-ld/lib
append_existing_path LD_LIBRARY_PATH /run/current-system/sw/lib
prepend_existing_path LD_LIBRARY_PATH "$APPDIR/usr/lib/x86_64-linux-gnu"
prepend_existing_path LIBGL_DRIVERS_PATH /run/opengl-driver/lib/dri
prepend_existing_path __EGL_VENDOR_LIBRARY_DIRS /run/opengl-driver/share/glvnd/egl_vendor.d

export HEARTHSTONE_LINUX_RESOURCES="$APPDIR/usr/share/hearthstone-linux-gui"
export HEARTHSTONE_LINUX_STUBS="$APPDIR/usr/share/hearthstone-linux-gui/stubs"

exec "$APPDIR/usr/bin/hearthstone-linux-gui" "$@"
